コメントを追加しました。
Rikuya-Matsuo/RBTact pull request #3
Opened 2019-05-11 04:20 UTC by Rikuya-Matsuo

レビューお願いします。

ーー内容ーー
Boss.h, Camera.h, Coin.h, Common.hにコメントを追加。
CoinControl, CoinMasterのクラス名、ファイル名を一般的に使われるものに変更。CoinGroup, CoinGroupManagerへ。これらにもコメント追加済み。

2019-05-13 02:18 UTC, vm-t-yui requested changes
コメントした部分を頑張って直してください
なおしたら私のコメントの下にどう直したか書いてください

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Camera.h
> +	void Init4Title();								//�^�C�g����ʂł̏���
[IMO]
〇〇forを〇〇4ってするのはちょっとなあ

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Boss.h
> +	void Anger();										//�{�X�̓{��t���O�𗧂Ă�֐��B�����ɂ��̎��Ԃ�L�^�B
Angerだけだと何をするのかわからないのでSetStateAngerとかのがいいのでは

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Boss.h
> +	bool sprit[PARTS_MASS_ALL];				//���̔ԍ��̃p�[�c�����􂵂����̃t���O
partsSplitFlagとかわかりやすい名前にしよう

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Boss.h
>  	int spritMass;						//���􂵂���
「回数」はmassではないかなあ

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Coin.cpp
> +void Coin::Obtained(Player * player, Effect *effect, CoinGroup *coinCtrl)
CoinGroupクラスになったのに引数がcoinCtrlのままです

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/Coin.h
> +	void Obtained(Player *player, Effect *effect, CoinGroup *coinCtrl);		//��肳���
OnObtainかな。シンプルにOnGetByでいい気がするけど

2019-05-13 02:18 UTC, vm-t-yui commented on work_RBTact/RabbitAction/main.cpp
> -				if (programControl.CheckHitDebugCmd(&pad))
デバッグ用なら#if _DEBUGで囲むか、〇〇Debugと名前をつけたい

2019-05-13 13:40 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Camera.h
> +	void Init4Title();								//�^�C�g����ʂł̏���
関数名Init4TitleをInitForTitleに修正しました。

2019-05-13 13:41 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Boss.h
> +	void Anger();										//�{�X�̓{��t���O�𗧂Ă�֐��B�����ɂ��̎��Ԃ�L�^�B
関数名AngerをSetAngerFlagTrueに修正しました。

2019-05-13 13:46 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Coin.cpp
> +void Coin::Obtained(Player * player, Effect *effect, CoinGroup *coinCtrl)
CoinGroupクラスへのポインタ変数の名前をcoinGroupに修正しました。

2019-05-13 13:46 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Coin.h
> +	void Obtained(Player *player, Effect *effect, CoinGroup *coinCtrl);		//��肳���
関数名ObtainedをOnObtainに修正しました。

2019-05-13 13:50 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/main.cpp
> -				if (programControl.CheckHitDebugCmd(&pad))
ファイルの先頭にDEBUGマクロを定義。
ブレイクポイント突入用の文は#ifdef DEBUGと#endif DEBUGで囲むことで、DEBUGマクロの定義がない場合は無効化されるように変更。

2019-05-13 13:55 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Boss.h
> +	bool sprit[PARTS_MASS_ALL];				//���̔ԍ��̃p�[�c�����􂵂����̃t���O
変数名spritをpartsSplitFlagに修正しました。

2019-05-13 13:57 UTC, Rikuya-Matsuo commented on work_RBTact/RabbitAction/Boss.h
>  	int spritMass;						//���􂵂���
変数名spritMassをsplitTimesに修正しました。

2019-05-14 02:02 UTC, vm-t-yui approved these changes
good

2019-05-15 02:52 UTC, merged